imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
#twig:
#    debug:            "%kernel.debug%"
#    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            varchar[]: StringArray
            StringArray: StringArray

        types:
            StringArray:     AppBundle\Model\DBAL\Type\StringArrayType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                connection: default
                query_cache_driver:
                    type:                 "%orm_query_cache_driver_type%" # Required
                metadata_cache_driver:
                    type:                 "%orm_metadata_cache_driver_type%" # Required
                result_cache_driver:
                    type:                 "%orm_result_cache_driver_type%" # Required
                naming_strategy: "doctrine.orm.naming_strategy.underscore"
                auto_mapping: true
                mappings:
                    # An array of mappings, which may be a bundle name or something else
                    ci_test:
                        mapping:              true
                        type:                 "annotation"
                        dir:                  "%kernel.root_dir%/../src/AppBundle/Model/Entity"
                        alias:                "ct"
                        prefix:               "AppBundle\\Model\\Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
