# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    jms_serializer.json_serialization_visitor.options: 128 #'@=constant("JSON_PRETTY_PRINT")'

services:

    command.import:
        class: AppBundle\Command\ImportCommand
        calls:
            - [setImporter, ["@downloading_importer"]]
        tags:
            -  { name: console.command }

    command.query:
        class: AppBundle\Command\QueryCommand
        calls:
            - [setSerializer, ["@jms_serializer"]]
            - [setPathFinder, ["@pathfinder"]]
        tags:
            -  { name: console.command }

    downloading_importer:
        class: AppBundle\Service\DownloadingImporter
        autowire: true
        arguments:
            - "%default_graph_download_file%"

    importer:
        class: AppBundle\Service\Import\Importer
        autowire: true

    downloader:
        class: AppBundle\Service\Download\Downloader
        autowire: true
        arguments:
            - "%download_folder%"

    pathfinder:
        class: AppBundle\Service\PathFinding\PathFinder
        autowire: true

    repository.path:
        class: AppBundle\Service\Repository\PathRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [\AppBundle\Model\Entity\PathEntity]

    jms_serializer.object_constructor:
        alias: "jms_serializer.enhanced_doctrine_object_constructor"
        public: false

    jms_serializer.enhanced_doctrine_object_constructor:
        class: AppBundle\Service\Serializer\Construction\DoctrineObjectConstructor
        arguments:
              - "@doctrine"
              - "@jms_serializer.unserialize_object_constructor"

    jms_serializer.entity_handler:
        class: AppBundle\Service\Serializer\IdHavingHandler
        arguments: [ "AppBundle\\Model\\Entity" ]
        autowire: true
        tags:
            -  { name: jms_serializer.subscribing_handler }

    jms_serializer.listener.post_deserialization_persist:
        class: AppBundle\Service\Serializer\EventHandler\PostDeserializeDoctrinePersist
        autowire: true
        tags:
            - { name: jms_serializer.event_subscriber }

    jms_serializer.listener.post_deserialization_graph_assign:
        class: AppBundle\Service\Serializer\EventHandler\PostDeserializeGraphAssign
        autowire: true
        tags:
            - { name: jms_serializer.event_subscriber }

    # guzzle http client
    guzzlehttp.client:
        class: GuzzleHttp\Client
        autowiring_types: GuzzleHttp\ClientInterface
